// courseData.js - আপনার StartingCourse কম্পোনেন্টের জন্য

export const courseData = [
  {
    id: 1,
    name: 'Language',
    title: 'Principles of Written English, Part 2',
    img: 'https://images.unsplash.com/photo-1555431189-0fabf2667795?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
    price: 40,
    details:
      'Master the principles of written English with comprehensive lessons, exercises, and real-world examples.',
    startDate: '2024-02-15',
    duration: '8 weeks',
    level: 'Beginner',
    instructor: 'Dr. Sarah Mitchell',
    instructorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    category: 'Language',
    students: 324,
    rating: 4.8,
    reviews: 156,
    description: `This comprehensive course is designed to help you master the principles of written English. 
    Whether you're a native speaker looking to polish your skills or a non-native speaker aiming to improve your written communication, 
    this course has something for everyone. We cover grammar, punctuation, style, and structure with real-world examples and 
    practical exercises that you can immediately apply to your writing.`,
    highlights: [
      'Grammar mastery and common mistakes',
      'Paragraph structure and organization',
      'Essay writing techniques',
      'Professional email writing',
      'Academic writing standards',
      '30+ interactive exercises',
    ],
    prerequisites: 'Basic English knowledge',
    learningOutcomes: [
      'Write grammatically correct sentences',
      'Structure essays effectively',
      'Understand English punctuation rules',
      'Develop a strong writing style',
      'Apply proofreading techniques',
    ],
    syllabus: [
      { week: 1, topic: 'Grammar Fundamentals', hours: 5 },
      { week: 2, topic: 'Sentence Structure', hours: 5 },
      { week: 3, topic: 'Paragraph Writing', hours: 6 },
      { week: 4, topic: 'Essay Basics', hours: 6 },
      { week: 5, topic: 'Advanced Grammar', hours: 5 },
      { week: 6, topic: 'Professional Writing', hours: 5 },
      { week: 7, topic: 'Style and Tone', hours: 6 },
      { week: 8, topic: 'Revision and Proofreading', hours: 6 },
    ],
    materials: [
      'Video lectures',
      'PDF worksheets',
      'Grammar guides',
      'Sample essays',
      'Writing templates',
    ],
    certificate: true,
    lifetime_access: true,
  },
  {
    id: 2,
    name: 'Computer',
    title: 'Introduction to Computer Science',
    img: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
    price: 100,
    details:
      'Learn the fundamentals of computer science including algorithms, data structures, and programming concepts.',
    startDate: '2024-02-20',
    duration: '10 weeks',
    level: 'Beginner',
    instructor: 'Prof. John Anderson',
    instructorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    category: 'Computer Science',
    students: 587,
    rating: 4.9,
    reviews: 289,
    description: `Dive into the world of computer science with this comprehensive introductory course. 
    Learn fundamental concepts that form the foundation of all programming and software development. 
    This course covers algorithms, data structures, computational thinking, and introduces you to programming basics. 
    Perfect for beginners who want to start their journey in tech.`,
    highlights: [
      'Algorithms and problem solving',
      'Data structures (arrays, linked lists, trees)',
      'Computational complexity',
      'Basic programming concepts',
      'Object-oriented programming intro',
      'Hands-on coding projects',
    ],
    prerequisites: 'No prior experience needed',
    learningOutcomes: [
      'Understand algorithmic thinking',
      'Work with common data structures',
      'Analyze code complexity',
      'Write basic programs',
      'Solve computational problems',
    ],
    syllabus: [
      { week: 1, topic: 'Introduction to CS', hours: 5 },
      { week: 2, topic: 'Algorithms Basics', hours: 6 },
      { week: 3, topic: 'Data Structures Part 1', hours: 6 },
      { week: 4, topic: 'Data Structures Part 2', hours: 6 },
      { week: 5, topic: 'Sorting Algorithms', hours: 5 },
      { week: 6, topic: 'Searching Algorithms', hours: 5 },
      { week: 7, topic: 'Programming Basics', hours: 7 },
      { week: 8, topic: 'Project Development', hours: 8 },
      { week: 9, topic: 'Advanced Concepts', hours: 6 },
      { week: 10, topic: 'Capstone Project', hours: 8 },
    ],
    materials: [
      'Video lectures',
      'Code examples',
      'Interactive quizzes',
      'Project assignments',
      'Coding challenges',
    ],
    certificate: true,
    lifetime_access: true,
  },
  {
    id: 3,
    name: 'Medicine',
    title: 'Introduction to Biomedical Imaging',
    img: 'https://images.unsplash.com/photo-1614294168453-84a363686839?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 400,
    details:
      'Explore the latest techniques in biomedical imaging and their clinical applications.',
    startDate: '2024-03-01',
    duration: '12 weeks',
    level: 'Advanced',
    instructor: 'Dr. Emily Chen',
    instructorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    category: 'Medicine',
    students: 234,
    rating: 4.7,
    reviews: 98,
    description: `This advanced course explores the fascinating world of biomedical imaging techniques. 
    Learn about MRI, CT scans, ultrasound, PET imaging, and more. Understand the physics behind these technologies, 
    their clinical applications, and how they're revolutionizing modern medicine. This course is designed for healthcare 
    professionals and those with a strong interest in medical technology.`,
    highlights: [
      'Medical imaging modalities',
      'Image acquisition techniques',
      'Clinical applications',
      'Image analysis and interpretation',
      'Safety and radiation protection',
      'Latest imaging technologies',
    ],
    prerequisites: 'Basic knowledge of physics and anatomy',
    learningOutcomes: [
      'Understand imaging physics',
      'Interpret medical images',
      'Apply imaging in clinical settings',
      'Analyze imaging data',
      'Stay updated with new technologies',
    ],
    syllabus: [
      { week: 1, topic: 'Fundamentals of Medical Imaging', hours: 6 },
      { week: 2, topic: 'X-ray and CT Technology', hours: 6 },
      { week: 3, topic: 'MRI Basics', hours: 7 },
      { week: 4, topic: 'MRI Advanced Topics', hours: 7 },
      { week: 5, topic: 'Ultrasound Imaging', hours: 6 },
      { week: 6, topic: 'Nuclear Imaging (PET/SPECT)', hours: 7 },
      { week: 7, topic: 'Image Reconstruction', hours: 6 },
      { week: 8, topic: 'Clinical Applications', hours: 7 },
      { week: 9, topic: 'Image Analysis', hours: 7 },
      { week: 10, topic: 'Safety and Quality', hours: 6 },
      { week: 11, topic: 'Emerging Technologies', hours: 6 },
      { week: 12, topic: 'Research Project', hours: 8 },
    ],
    materials: [
      'Video lectures',
      'Medical imaging software',
      'Case studies',
      'Research papers',
      'Lab simulations',
    ],
    certificate: true,
    lifetime_access: true,
  },
  {
    id: 4,
    name: 'Marketing',
    title: 'Entrepreneurship 101: Who is your customer?',
    img: 'https://plus.unsplash.com/premium_photo-1661414415246-3e502e2fb241?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 40,
    details:
      'Learn how to identify and understand your target customer for successful entrepreneurship.',
    startDate: '2024-02-25',
    duration: '6 weeks',
    level: 'Beginner',
    instructor: 'Mark Thompson',
    instructorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mark',
    category: 'Business',
    students: 456,
    rating: 4.6,
    reviews: 203,
    description: `Starting a business? The most important first step is understanding your customer. 
    This practical course teaches you how to identify, research, and understand your target audience. 
    Learn market research techniques, customer profiling, and how to validate your business idea. 
    Perfect for aspiring entrepreneurs and small business owners.`,
    highlights: [
      'Market research techniques',
      'Creating customer personas',
      'Customer journey mapping',
      'Competitive analysis',
      'Validation strategies',
      'Real-world case studies',
    ],
    prerequisites: 'No prerequisites',
    learningOutcomes: [
      'Identify target market segments',
      'Create detailed customer personas',
      'Conduct market research',
      'Validate business ideas',
      'Build customer-centric strategies',
    ],
    syllabus: [
      { week: 1, topic: 'Entrepreneurship Basics', hours: 5 },
      { week: 2, topic: 'Market Research Methods', hours: 6 },
      { week: 3, topic: 'Customer Profiling', hours: 6 },
      { week: 4, topic: 'Competitive Analysis', hours: 5 },
      { week: 5, topic: 'Validation Techniques', hours: 6 },
      { week: 6, topic: 'Business Planning', hours: 6 },
    ],
    materials: [
      'Video lectures',
      'Research templates',
      'Case studies',
      'Interview guides',
      'Planning worksheets',
    ],
    certificate: true,
    lifetime_access: true,
  },
  {
    id: 5,
    name: 'Social',
    title: 'Principles of Written Social, Part 2',
    img: 'https://plus.unsplash.com/premium_photo-1678914045640-55a120a8f849?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    price: 'Free',
    details: 'Understand social dynamics and written communication in the modern world.',
    startDate: '2024-03-05',
    duration: '4 weeks',
    level: 'Beginner',
    instructor: 'Rachel Williams',
    instructorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
    category: 'Social Sciences',
    students: 892,
    rating: 4.5,
    reviews: 412,
    description: `Navigate the complexities of social communication in the digital age. 
    This course explores how written communication shapes social interactions, cultural norms, and community building. 
    Learn the art of meaningful digital communication and how to engage authentically in online spaces.`,
    highlights: [
      'Digital communication etiquette',
      'Online community dynamics',
      'Social media writing',
      'Conflict resolution',
      'Inclusive communication',
      'Cultural sensitivity',
    ],
    prerequisites: 'No prerequisites',
    learningOutcomes: [
      'Master social communication skills',
      'Build meaningful online relationships',
      'Write with cultural awareness',
      'Resolve conflicts diplomatically',
      'Engage authentically online',
    ],
    syllabus: [
      { week: 1, topic: 'Digital Communication Basics', hours: 4 },
      { week: 2, topic: 'Community Building', hours: 5 },
      { week: 3, topic: 'Conflict & Resolution', hours: 5 },
      { week: 4, topic: 'Cultural Communication', hours: 4 },
    ],
    materials: [
      'Video lectures',
      'Discussion guides',
      'Reflection prompts',
      'Community examples',
    ],
    certificate: false,
    lifetime_access: true,
  },
  {
    id: 6,
    name: 'Digital Marketing',
    title: 'Principles of Digital Marketing, Part 2',
    img: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1415&q=80',
    price: 40,
    details:
      'Master digital marketing strategies, SEO, social media marketing, and content creation.',
    startDate: '2024-03-10',
    duration: '8 weeks',
    level: 'Intermediate',
    instructor: 'David Martinez',
    instructorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    category: 'Marketing',
    students: 643,
    rating: 4.8,
    reviews: 287,
    description: `Master the complete digital marketing landscape in this comprehensive course. 
    Learn SEO, social media marketing, email campaigns, content marketing, and analytics. 
    Understand how to drive traffic, increase conversions, and build a strong online presence. 
    Ideal for marketing professionals and entrepreneurs.`,
    highlights: [
      'SEO and keyword research',
      'Social media marketing strategies',
      'Content marketing excellence',
      'Email marketing automation',
      'Analytics and measurement',
      'Paid advertising campaigns',
    ],
    prerequisites: 'Basic marketing knowledge helpful',
    learningOutcomes: [
      'Implement effective SEO strategies',
      'Create viral social media content',
      'Build email marketing funnels',
      'Analyze marketing metrics',
      'Launch successful campaigns',
    ],
    syllabus: [
      { week: 1, topic: 'Digital Marketing Overview', hours: 5 },
      { week: 2, topic: 'SEO Fundamentals', hours: 6 },
      { week: 3, topic: 'Social Media Strategy', hours: 6 },
      { week: 4, topic: 'Content Marketing', hours: 6 },
      { week: 5, topic: 'Email Marketing', hours: 5 },
      { week: 6, topic: 'Paid Advertising', hours: 6 },
      { week: 7, topic: 'Analytics & Metrics', hours: 5 },
      { week: 8, topic: 'Campaign Integration', hours: 6 },
    ],
    materials: [
      'Video lectures',
      'SEO tools guide',
      'Templates',
      'Case studies',
      'Analytics dashboards',
    ],
    certificate: true,
    lifetime_access: true,
  },
];
